
post_install() {
    echo "Create the django database with: cd /opt/graphite ; PYTHONPATH=/opt/graphite/webapp django-admin2.py syncdb --settings=graphite.settings"
    echo "Run Carbon with 'systemctl start carbon'."
    echo "Run Graphite webserver with 'uwsgi --ini /opt/graphite/conf/uwsgi-graphite.ini'. (requires uwsgi) ;"
    echo "Or point Passenger-enabled webserver at /opt/graphite/webapp/graphite/public"
    echo "Also note that Graphite listens on port 2003 by default and this package configures the webserver to listen on port 81 by default."
    echo "So, you might want to filter who can access those ports, for instance with iptables."
}
